# Metodologías para cálculo del VaR - Documentación

In [1]:
from methodologies import methodology

In [2]:
activos = ["BA", "AMZN", "AAPL", "AAL", "GS"]
dinero = [100, 100, 100, 100, 100]
desde = "2018-04-03"
hasta = "2020-05-08"
alphas = [0.1,  0.05,  0.025,  0.01]
periodos = 277

M = methodology(stocks=activos, 
                 amount = dinero,
                 init = desde, 
                 end = hasta,
                 alphas = alphas,
                 periods=periodos)

### Estadísticos

In [3]:
M.get_statistics()

                      BA     AMZN      AAPL       AAL        GS
Participacion      20.0%    20.0%     20.0%     20.0%     20.0%
Precio Cierre     133.44  2379.61   77.5325     10.14    185.39
Rendimiento       3.656%   0.506%    2.082%    6.099%     1.67%
Media            -0.172%   0.101%    0.115%   -0.307%   -0.057%
Desv. estándar    3.502%    2.08%    2.232%    3.861%    2.308%
Varianza          0.123%   0.043%     0.05%    0.149%    0.053%
Curtosis         18.2335  2.96949   7.13351   15.2162   12.9899
Mínimo          -27.244%  -8.254%  -13.771%  -29.068%  -13.588%
Máximo           21.768%   9.025%   11.316%   30.605%   16.195%
Cantidad             529      529       529       529       529

### Metodologías para VaR individual:

In [4]:
M.VaRDeltaNormal("BA")
M.VaRSimulacionHistoricaUnivariada("AAL")
M.VaRDeltaT("GS")

         Fechas     p=0.1    p=0.05   p=0.025    p=0.01
0       VaR t+1 -0.033216 -0.045350 -0.057853 -0.075731
1    04/04/2019 -0.018297 -0.024981 -0.031868 -0.041716
2    05/04/2019 -0.018294 -0.024977 -0.031863 -0.041708
3    08/04/2019 -0.018268 -0.024942 -0.031818 -0.041651
4    09/04/2019 -0.018198 -0.024846 -0.031696 -0.041491
..          ...       ...       ...       ...       ...
273  04/05/2020 -0.033146 -0.045254 -0.057731 -0.075570
274  05/05/2020 -0.033135 -0.045240 -0.057712 -0.075546
275  06/05/2020 -0.033147 -0.045257 -0.057734 -0.075574
276  07/05/2020 -0.033126 -0.045228 -0.057696 -0.075525
277  08/05/2020 -0.033194 -0.045321 -0.057815 -0.075681

[278 rows x 5 columns]

### Metodologías para VaR Portafolio:

In [5]:
M.VaRSumaSimple()
M.VaRBaricentroEWMANormal()
M.VaRBaricentroPromedioNormal()
M.VaRSimulacionHistorica()
M.VaRBaricentroPromedioT()
M.VaRBaricentroEWMAT()
M.VaRMatrizVarCovar()

         Fechas     p=0.1    p=0.05   p=0.025    p=0.01
0       VaR t+1 -0.035073 -0.045016 -0.053639 -0.063666
1    04/04/2019 -0.019954 -0.025611 -0.030517 -0.036222
2    05/04/2019 -0.019955 -0.025612 -0.030518 -0.036223
3    08/04/2019 -0.019916 -0.025562 -0.030459 -0.036153
4    09/04/2019 -0.019776 -0.025382 -0.030245 -0.035898
..          ...       ...       ...       ...       ...
273  04/05/2020 -0.034980 -0.044896 -0.053497 -0.063498
274  05/05/2020 -0.034966 -0.044878 -0.053476 -0.063472
275  06/05/2020 -0.034969 -0.044882 -0.053480 -0.063477
276  07/05/2020 -0.034921 -0.044820 -0.053407 -0.063390
277  08/05/2020 -0.034994 -0.044914 -0.053519 -0.063523

[278 rows x 5 columns]

### BackTesting

In [6]:
M.BackTesting(M.VaRSimulacionHistorica())

                                p=0.1      p=0.05     p=0.025      p=0.01
x                                  35          22          15           9
m                                 277         277         277         277
p estimado                   0.126354   0.0794224   0.0541516    0.032491
nivel de significancia           0.05        0.05        0.05        0.05
test de kupiec                1.98997     4.31638     7.28124     8.89341
Valor P                      0.104561   0.0221851  0.00387887  0.00156746
Zona de rechazo         No Rechazo H0  Rechazo H0  Rechazo H0  Rechazo H0
BackTesting                      27.7       13.85       6.925        2.77
Valor de eficiencia          0.873646    0.920578    0.945848    0.967509